// <auto-generated />
namespace Information_Center.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CourseAttribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CourseAttribute));
        
        string IMigrationMetadata.Id
        {
            get { return "202107302226299_CourseAttribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
